# Generated by Django 6.0.3 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm_companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployed_from_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployed_from_state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
